Repository observablehq/plot, pull requests merged in 2022-12, with the labels that each got.

#1147 sharper translate
  src/projection.js
Labels: geo

#1144 document the bundle curve
  README.md
Labels: documentation

#1151 projection.clip option
  README.md
  src/projection.js
  test/data/README.md
  test/data/countries-110m.json
  test/output/armadillo.svg
  test/output/projectionBleedEdges.svg
  test/output/projectionBleedEdges2.svg
  test/output/projectionClipAngle.svg
  test/output/projectionClipAngleFrame.svg
  test/output/projectionClipBerghaus.svg
  test/output/projectionFitAntarctica.svg
  test/output/projectionFitBertin1953.svg
  test/output/projectionFitConic.svg
  test/output/usCountyChoropleth.html
  test/output/usStateCapitals.svg
  test/plots/bertin1953-facets.js
  test/plots/index.js
  test/plots/projection-bleed-edges.js
  test/plots/projection-bleed-edges2.js
  test/plots/projection-clip-angle-frame.js
  test/plots/projection-clip-angle.js
  test/plots/projection-clip-berghaus.js
  test/plots/projection-fit-antarctica.js
  test/plots/projection-fit-bertin1953.js
  test/plots/projection-fit-conic.js
Labels: enhancement, geo

#1156 curve: "projection"
  README.md
  src/marks/line.js
  test/data/README.md
  test/data/beagle.csv
  test/output/beagle.svg
  test/plots/beagle.js
  test/plots/index.js
Labels: enhancement, geo

#1139 projection support for x1/y1 x2/y2 marks
  README.md
  src/channel.js
  src/marks/rect.js
  src/projection.js
  test/marks/rule-test.js
  test/output/boundingBoxes.svg
  test/plots/bounding-boxes.js
  test/plots/index.js
Labels: enhancement, geo

#1163 symbol ratio
  src/projection.js
Labels: geo

#1189 spike vector shape + centroid transforms
  README.md
  src/index.js
  src/marks/dot.js
  src/marks/text.js
  src/marks/vector.js
  src/template.js
  src/transforms/centroid.js
  test/data/us-county-population.csv
  test/output/caltrainDirection.svg
  test/output/countryCentroids.svg
  test/output/shorthandVector.svg
  test/output/shorthandVectorX.svg
  test/output/usCountySpikes.svg
  test/output/usPresidentialElectionMap2020.svg
  test/output/vectorField.svg
  test/output/vectorFrame.svg
  test/plots/country-centroids.js
  test/plots/index.js
  test/plots/us-county-spikes.js
  test/plots/us-presidential-election-map-2020.js
Labels: geo
